### ISSUE TITLE
Tabbed Workflow - Incorrect Code

### ISSUE THREAD

**Issue by chathuraa** [node-on-fhir/cookbook#33]
Hey Abigail,

I found few issues with the code. I think it should be

``` javascript
Template.samplePage.firstPanelVisibility = function(){
  if(Session.get('selectedPanel') === 1){
    return "visible";
  }else{
    return "hidden";
  }
}
Template.samplePage.secondPanelVisibility = function(){
  if(Session.get('selectedPanel') === 2){
    return "visible";
  }else{
    return "hidden";
  }
}
Template.samplePage.thirdPanelVisibility = function(){
  if(Session.get('selectedPanel') === 3){
    return "visible";
  }else{
    return "hidden";
  }
}
Template.samplePage.firstPanelActive = function(){
  if(Session.get('selectedPanel') === 1){
    return "active panel-tab";
  }else{
    return "panel-tab";
  }
}
Template.samplePage.secondPanelActive= function(){
  if(Session.get('selectedPanel') === 2){
    return "active panel-tab";
  }else{
    return "panel-tab";
  }
}
Template.samplePage.thirdPanelActive = function(){
  if(Session.get('selectedPanel') === 3){
    return "active panel-tab";
  }else{
    return "panel-tab";
  }
}
```

and the css should be like the following. This will still affect the flow of the document.

``` css
.visible{
  visibility: visible;
}
.hidden{
  visibility: hidden;
}
```

Better implementation might be

``` css
.show {
  display: block !important;
  visibility: visible !important;
}
.hidden {
  display: none !important;
  visibility: hidden !important;
}
```
